### ISSUE TITLE
docker compile failing at numpy/cython

### ISSUE THREAD

**Issue by Sfinx** [sipeed/R329-Tina-jishu#6]
```
 make[3] -C package/lang/python3-numpy compile
Running from numpy source directory.

Error compiling Cython file:
------------------------------------------------------------
...
        for i in range(1, RK_STATE_LEN):
            self.rng_state.key[i] = val[i]
        self.rng_state.pos = i

        self._bitgen.state = &self.rng_state
        self._bitgen.next_uint64 = &mt19937_uint64
                                   ^
------------------------------------------------------------

_mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
Traceback (most recent call last):
  File "/t/out/r329-evb5/compile_dir/target/numpy-1.19.2/tools/cythonize.py", line 235, in <module>
    main()
  File "/t/out/r329-evb5/compile_dir/target/numpy-1.19.2/tools/cythonize.py", line 231, in main
    find_process_files(root_dir)
  File "/t/out/r329-evb5/compile_dir/target/numpy-1.19.2/tools/cythonize.py", line 222, in find_process_files
    process(root_dir, fromfile, tofile, function, hash_db)
  File "/t/out/r329-evb5/compile_dir/target/numpy-1.19.2/tools/cythonize.py", line 188, in process
    processor_function(fromfile, tofile)
  File "/t/out/r329-evb5/compile_dir/target/numpy-1.19.2/tools/cythonize.py", line 78, in process_pyx
    [sys.executable, '-m', 'cython'] + flags + ["-o", tofile, fromfile])
  File "/t/out/r329-evb5/staging_dir/target/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/t/out/host/bin/python3', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
```

**Comment by TianQingshuai** [comment]
same here
